Skip a scan test scenario if no automatic ice servers are found for the scenario unless it's the host test.
liveswitch/liveswitch-hammer pull request #14
Opened 2021-09-13 18:05 UTC by hardeep-fm

2021-09-13 18:14 UTC, andriy-baranskyy approved these changes

2021-09-13 20:10 UTC, avenema requested changes

2021-09-13 20:10 UTC, avenema commented on src/FM.LiveSwitch.Hammer/ScanTestMediaServer.cs
> +                                    result.SetScenarioResult(scenario, ScanTestScenarioResult.Skip(scenario, "Skipped due to no ice servers."));
Suggested wording:

`"No ICE servers."`

"ICE" as an acronym should be capitalized "Skipped due to" is redundant -- the scenario result is already "skipped" and the message is the reason.

2021-09-13 20:10 UTC, avenema commented on src/FM.LiveSwitch.Hammer/ScanTestMediaServer.cs
> +                    throw new NoIceServersException($"No ICE Servers found for {scenario.ToDisplayString()}.");
`Servers` should be `servers`.

2021-09-13 20:10 UTC, avenema commented on src/FM.LiveSwitch.Hammer/ScanTestMediaServer.cs
> +                    Console.Error.WriteLine($"No ICE Servers found.");
`Servers` should be `servers`.

2021-10-01 16:05 UTC, avenema approved these changes

2021-10-01 16:05 UTC, merged